"""New Migration

Revision ID: 838bc06b8bb9
Revises: 
Create Date: 2023-12-13 16:07:22.613501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838bc06b8bb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icd10_codes', sa.JSON(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('elig', sa.String(), nullable=True),
    sa.Column('orec', sa.String(), nullable=True),
    sa.Column('medicaid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('hcc_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_score_age', sa.Float(), nullable=True),
    sa.Column('risk_score_adj', sa.Float(), nullable=True),
    sa.Column('risk_score_age_adj', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('hcc_lst', sa.JSON(), nullable=True),
    sa.Column('hcc_map', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hcc_profiles')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
